swagger: "2.0"
info:
description: "APIs for managing addresses and appliances"
version: "1.0.0"
title: "Address and Appliance API"
basePath: "/"
schemes:
- "http"
- "https"
  paths:
  /save-address:
  post:
  tags:
    - "Address"
      summary: "Save address details"
      consumes:
    - "application/json"
      produces:
    - "application/json"
      parameters:
    - in: "body"
      name: "addressDetails"
      description: "Address details to be saved"
      required: true
      schema:
      $ref: "#/definitions/AddressesDetails"
      responses:
      200:
      description: "OK"
      schema:
      type: "object"
      properties:
      Status:
      type: "string"
      example: "success"
      /get-address:
      post:
      tags:
    - "Address"
      summary: "Get address details"
      consumes:
    - "application/json"
      produces:
    - "application/json"
      parameters:
    - in: "body"
      name: "userDetails"
      description: "User details for getting address details"
      required: true
      schema:
      $ref: "#/definitions/UserDetails"
      responses:
      200:
      description: "OK"
      schema:
      type: "object"
      properties:
      Data:
      type: "array"
      items:
      $ref: "#/definitions/AddressesDetails"
      /save-appliance:
      post:
      tags:
    - "Appliance"
      summary: "Save appliance details"
      consumes:
    - "application/json"
      produces:
    - "application/json"
      parameters:
    - in: "body"
      name: "applianceDetails"
      description: "Appliance details to be saved"
      required: true
      schema:
      $ref: "#/definitions/ApplianceDetails"
      responses:
      200:
      description: "OK"
      schema:
      type: "object"
      properties:
      Status:
      type: "string"
      example: "success"
